apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: nfs-encrypted
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi