apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: 25565
    targetPort: 25565
    name: {{ .Release.Name }}
  type: LoadBalancer