apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-1-15-1
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-1-15-1
  template:
    metadata:
      labels:
        app: minecraft-1-15-1
    spec:
      containers:
      - name: minecraft-1-15-1
        image: ducoterra/minecraft_1.15.1:0.0.8
        ports:
        - containerPort: 25565
        volumeMounts:
        - mountPath: /mc_data
          name: data
        tty: true
        stdin: true
        env:
        - name: MAX_RAM
          value: "4"
        - name: MIN_RAM
          value: "1"
        - name: THREADS
          value: "4"
        resources:
          requests:
            memory: 1Mi
            cpu: 1m
          limits:
            memory: "4Gi"
            cpu: "4"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-1-15-1
