apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: hub.ducoterra.net/ducoterra/minecraft:20w12a.7
        ports:
        - containerPort: 25565
        volumeMounts:
        - mountPath: /mc_data
          name: data
        tty: true
        stdin: true
        env:
        - name: MAX_RAM
          value: "4"
        - name: MIN_RAM
          value: "1"
        - name: THREADS
          value: "4"
        resources:
          requests:
            memory: "2Gi"
            cpu: 250m
          limits:
            memory: "4Gi"
            cpu: "4"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft
