apiVersion: v1
kind: Service
metadata:
  name: minecraft-1-15-1
  namespace: minecraft
spec:
  selector:
    app: minecraft-1-15-1
  ports:
  - port: 25565
    targetPort: 25565
    name: minecraft
  type: LoadBalancer