apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-1-15-1
  namespace: minecraft
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi